### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by JingpengSun** [MaigoAkisame/cmu-thesis#1]
Hi, thank you for your great work!
when I run the ./download.sh
I got the following:
Connecting to islpc21.is.cs.cmu.edu(islpc21.is.cs.cmu.edu)|128.2.190.16|:80... failed:  Connection time out.

I checked the computer is connected to the Internet.
Is that something wrong with the your sever?

**Comment by MaigoAkisame** [comment]
Seems I don't have the problem...

Can you try and see if you can open the following path in your browser?
http://islpc21.is.cs.cmu.edu/yunwang/git/cmu-thesis/data/

**Comment by JingpengSun** [comment]
I can open this path in browser and now it's ok in terminal.
Thank you~
